# Generated by Django 4.0.4 on 2022-08-15 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rareuser',
            name='active',
        ),
        migrations.RemoveField(
            model_name='rareuser',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='rareuser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='rareuser',
            name='username',
        ),
    ]
