# Generated by Django 4.0.4 on 2022-08-15 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0002_comment'),
        ('app_api', '0002_tag_posttag'),
    ]

    operations = [
    ]
