# Generated by Django 4.1 on 2022-08-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0003_merge_0002_comment_0002_tag_posttag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(related_name='posts', through='app_api.PostTag', to='app_api.tag'),
        ),
    ]
