# Generated by Django 4.0.4 on 2022-08-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0004_comment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='subject',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
