# Generated by Django 4.1 on 2022-08-16 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0004_post_tags'),
        ('app_api', '0005_comment_subject'),
    ]

    operations = [
    ]
