
# Generated by Django 4.1 on 2022-08-17 15:18

# Generated by Django 4.1 on 2022-08-17 18:05


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0004_post_tags'),
        ('app_api', '0005_comment_subject'),
    ]

    operations = [
    ]
