# Generated by Django 4.0.4 on 2022-08-17 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0006_merge_0004_post_tags_0005_comment_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='date',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='post_id',
            new_name='post',
        ),
    ]
