# Generated by Django 4.1 on 2022-08-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0007_reaction_postreaction_post_reactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rareuser',
            name='profile_image_url',
            field=models.ImageField(null=True, upload_to='profileimages'),
        ),
    ]
