# Generated by Django 4.0.4 on 2022-08-18 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0007_reaction_postreaction_post_reactions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postreaction',
            name='user',
        ),
    ]
