# Generated by Django 4.1 on 2022-08-18 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0007_reaction_postreaction_post_reactions'),
        ('app_api', '0007_rename_author_id_comment_author_and_more'),
    ]

    operations = [
    ]
