# Generated by Django 4.1 on 2022-08-18 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0008_alter_rareuser_profile_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approveUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firstapproved', to='app_api.rareuser')),
                ('demotedUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demoted', to='app_api.rareuser')),
                ('secondApproveUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondapproved', to='app_api.rareuser')),
            ],
        ),
    ]
