# Generated by Django 4.1 on 2022-08-18 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0007_rename_author_id_comment_author_and_more'),
        ('app_api', '0008_alter_rareuser_profile_image_url'),
        ('app_api', '0009_alter_post_image_url'),
    ]

    operations = [
    ]
