# Generated by Django 4.1 on 2022-08-18 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0008_alter_rareuser_profile_image_url'),
        ('app_api', '0008_merge_20220818_1815'),
        ('app_api', '0008_subscription'),
        ('app_api', '0009_alter_post_image_url'),
    ]

    operations = [
    ]
