# Generated by Django 4.1 on 2022-08-18 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0009_demote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demote',
            name='secondApproveUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondapproved', to='app_api.rareuser'),
        ),
    ]
