# Generated by Django 4.1 on 2022-08-18 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0007_rename_author_id_comment_author_and_more'),
        ('app_api', '0010_alter_demote_secondapproveuser'),
    ]

    operations = [
    ]
