# Generated by Django 4.1 on 2022-08-18 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0011_merge_20220818_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deactivate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approveUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firstdeactiveapproved', to='app_api.rareuser')),
                ('deactivatedUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deactivate', to='app_api.rareuser')),
                ('secondApproveUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seconddeactiveapproved', to='app_api.rareuser')),
            ],
        ),
    ]
