# Generated by Django 4.0.4 on 2022-08-19 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0010_merge_20220818_1948'),
        ('app_api', '0010_merge_20220818_1954'),
        ('app_api', '0012_deactivate'),
    ]

    operations = [
    ]
