# Generated by Django 4.0.4 on 2022-08-19 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0013_merge_0010_merge_20220818_2005_0012_deactivate'),
        ('app_api', '0013_merge_20220819_1456'),
    ]

    operations = [
    ]
