# Generated by Django 4.0.4 on 2022-08-19 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0014_merge_20220819_1713'),
        ('app_api', '0015_subscription_is_active'),
    ]

    operations = [
    ]
